// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX-O0kRfVAu3rg4taSbfZyF2M8-e22kM0',
    appId: '1:537461513868:web:509b7652260940899925a9',
    messagingSenderId: '537461513868',
    projectId: 'quickassist-612a6',
    authDomain: 'quickassist-612a6.firebaseapp.com',
    storageBucket: 'quickassist-612a6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKvET0xW9oi6Fc9FePtArjNs3U8UHjk_o',
    appId: '1:537461513868:android:7b41cac4bb514bf49925a9',
    messagingSenderId: '537461513868',
    projectId: 'quickassist-612a6',
    storageBucket: 'quickassist-612a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3pgmW7HjYK3Zgu7yDe-HjaTjSFNdGI6U',
    appId: '1:537461513868:ios:e449f8327550d3589925a9',
    messagingSenderId: '537461513868',
    projectId: 'quickassist-612a6',
    storageBucket: 'quickassist-612a6.appspot.com',
    iosBundleId: 'com.quickassist.quickassist',
  );
}
